version: "3.8"

services:
  frontend: 
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - ${ANTIMATTER_WEB_PORT}:${ANTIMATTER_WEB_PORT}
    env_file:
      - .env
    environment:
      - NEXTAUTH_URL=${ANTIMATTER_URL}
    depends_on:
      - backend

  backend:
    build: 
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules/
    ports:
      - ${ANTIMATTER_API_PORT}:${ANTIMATTER_API_PORT}
    env_file:
      - .env
    depends_on:
      - database

  database:
    image: mongo:latest
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27017:27017
    volumes:
      - "antimatter_database:/data/db"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'database:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 10s
      start_period: 30s

      # In production there should ideally be another rs node.

volumes:
  antimatter_database:

