version: "3.8"

services:
  frontend: 
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - ${ANTIMATTER_WEB_PORT}:${ANTIMATTER_WEB_PORT}
    env_file:
      - .env
    environment:
      - NEXTAUTH_URL=${ANTIMATTER_URL}
    depends_on:
      - backend

  backend:
    build: 
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules/
    ports:
      - ${ANTIMATTER_API_PORT}:${ANTIMATTER_API_PORT}
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - "antimatter_database:/data/db"
    healthcheck:
      test: echo 'db.stats().ok' | mongosh localhost:27017/antimatter --quiet
      interval: 10s
      start_period: 30s

      # In production there should ideally be another rs node.

volumes:
  antimatter_database:

